### ISSUE TITLE
About optical flow ground truth

### ISSUE THREAD

**Issue by Alllcher** [RIA1159/FacialFlowNet#1]
Hi,
I read your paper, FacialFlowNet: Advancing Facial Optical Flow Estimation with a Diverse Dataset and a Decomposed Model.
It is a outstanding work in Facial Optical Flow area.
I want to know how to generate flow label by Blender? 

#Ground Truth Generation: Modifying Blender’s internal render
 engine pipeline enables the passage of vectors between different
 frames. The render pass is typically used for producing motion blur
 [7, 13, 32, 33, 38], and it produces the motion in the image space of
 eachpixel; i.e., the ground truth of optical flow. Additionally, we also
 employ it to generate ground truth depth information, examples
 are available in the supplementary material.

**Comment by RIA1159** [comment]
You can use this plugin. 
https://github.com/Cartucho/vision_blender
